export default function DashboardPage() {
  return (
    <>
      <div className="bg-red-300 w-full h-full">
        <h2>ssss</h2>
        <h2>ssss</h2>
        <h2>ssss</h2>
        <h2>ssss</h2>
        <h2>ssss</h2>
        <h2>ssss</h2>
        <h2>ssss</h2>
        <h2>ssss</h2>
        <h2>ssss</h2>
        <h2>ssss</h2>
        <h2>ssss</h2>
        <h2>ssss</h2>
        <h2>ssss</h2>
        <h2>ssss</h2>
        <h2>ssss</h2>
        <h2>ssss</h2>
        <h2>ssss</h2>
        <h2>ssss</h2>
        <h2>ssss</h2>
        <h2>ssss</h2>
        <h2>ssss</h2>
        <h2>ssss</h2>
        <h2>ssss</h2>
        <h2>ssss</h2>
        <h2>ssss</h2>
        <h2>ssss</h2>
        <h2>ssss</h2>
        <h2>ssss</h2>
        <h2>ssss</h2>
        <h2>ssss</h2>
        <h2>ssss</h2>
      </div>
    </>
  );
}
